#######################################
# Environment Variables
#######################################

# Fcitx5
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULE,fcitx
env=QT_IM_MODULES,wayland;fcitx
env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=GLFW_IM_MODULE,ibus

#######################################
# Autostart
#######################################

# Screen Sharing
exec-once=/usr/lib/xdg-desktop-portal-wlr &

# Clipboard Manager
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist store &

#######################################
# Monitors
#######################################

# Monitor Rules
monitorrule=model:QEMU Monitor,width:1920,height:1080,refresh:60,x:0,y:0

# Tearing
allow_tearing=1

#######################################
# Input Devices
#######################################

# Keyboard Settings
repeat_rate=50
repeat_delay=200
numlockon=0
xkb_rules_layout=us

# Mouse Settings
mouse_natural_scrolling=0
mouse_accel_profile=0
mouse_accel_speed=0.0
mouse_left_handed=0
mouse_middle_button_emulation=0
mouse_scroll_method=1
mouse_scroll_button=274
mouse_click_method=1
mouse_send_events_mode=0
axis_scroll_factor=1.0

# Trackpad Settings
disable_trackpad=1
tap_to_click=1
tap_and_drag=1
trackpad_natural_scrolling=0
trackpad_accel_profile=2
trackpad_accel_speed=0.0
trackpad_scroll_button=274
trackpad_scroll_method=1
trackpad_click_method=1
trackpad_send_events_mode=0
drag_lock=1
trackpad_disable_while_typing=1
trackpad_left_handed=0
trackpad_middle_button_emulation=0
swipe_min_threshold=1
gesture_live=1
gesture_swipe_distance=300
gesture_swipe_cancel_ratio=0.5
gesture_swipe_min_speed_to_force=10
button_map=0
trackpad_scroll_factor=1.0

# Touchscreen Settings
touch_enable=0
touch_enable_mouse_emulation=0

#######################################
# Miscellaneous
#######################################

# System & Hardware
xwayland_persistence=1
xwayland_ignore_scale=0
syncobj_enable=1
allow_lock_transparent=0
allow_shortcuts_inhibit=1

# Focus & Input
focus_on_activate=1
sloppyfocus=1
warpcursor=1
cursor_hide_timeout=0
cursor_hide_on_keypress=1
drag_tile_to_tile=1
drag_tile_small=1
drag_corner=3
drag_warp_cursor=1
axis_bind_apply_timeout=100

# Multi-Monitor & Tags
focus_cross_monitor=0
focusdir_only_zone_overlap=1
exchange_cross_monitor=0
focus_cross_tag=0
view_current_to_back=0
scratchpad_cross_monitor=0
single_scratchpad=1
tag_num=9
tag_gather=0

# Window Behavior
enable_floating_snap=0
snap_distance=30
float_full_to_top=0
no_border_when_single=0
smartgaps=0
idleinhibit_ignore_visible=0
idleinhibit_when_fullscreen=0
tag_carousel=0
drag_tile_refresh_interval=8.0
drag_floating_refresh_interval=8.0
